row_id,dataset_name,llm_model,config,sub_task,error_class,error_type,error_value,error_detail,error_exception,file_name,timestamp
1,oml_dataset_5_rnc,gemini-1.5-pro-latest,CatDB,,KeyError,Exception-<class 'KeyError'>,Exception-<class 'KeyError'>,"['""c_9""'] not found in axis","Traceback (most recent call last):
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/runcode/RunCode.py"", line 36, in execute_code
    exec(compile(parse, filename=""<ast>"", mode=""exec""), loc)
  File ""<ast>"", line 24, in <module>
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/pandas/core/frame.py"", line 5344, in drop
    return super().drop(
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 4711, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/pandas/core/generic.py"", line 4753, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/pandas/core/indexes/base.py"", line 7000, in drop
    raise KeyError(f""{labels[mask].tolist()} not found in axis"")
KeyError: '[\'""c_9""\'] not found in axis'
",gemini-1.5-pro-latest-CatDB-Random-10-SHOT-No-iteration-1_0.python,2024-07-01T18:40:54.940723
2,oml_dataset_5_rnc,gemini-1.5-pro-latest,CatDB,,TypeError,Exception-<class 'TypeError'>,Exception-<class 'TypeError'>,"Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.","Traceback (most recent call last):
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/runcode/RunCode.py"", line 36, in execute_code
    exec(compile(parse, filename=""<ast>"", mode=""exec""), loc)
  File ""<ast>"", line 24, in <module>
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/sklearn/base.py"", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/sklearn/ensemble/_forest.py"", line 363, in fit
    X, y = self._validate_data(
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/sklearn/base.py"", line 608, in _validate_data
    self._check_feature_names(X, reset=reset)
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/sklearn/base.py"", line 469, in _check_feature_names
    feature_names_in = _get_feature_names(X)
  File ""/home/saeed/Documents/Github/CatDB/Experiments/setup/Baselines/CatDB/venv/lib/python3.10/site-packages/sklearn/utils/validation.py"", line 2250, in _get_feature_names
    raise TypeError(
TypeError: Feature names are only supported if all input features have string names, but your input has ['int', 'str'] as feature name / column name types. If you want feature names to be stored and validated, you must convert them all to strings, by using X.columns = X.columns.astype(str) for example. Otherwise you can remove feature / column names from your input data, or convert them all to a non-string data type.
",gemini-1.5-pro-latest-CatDB-Random-10-SHOT-No-iteration-1_1.python,2024-07-01T18:41:44.322013
